# This is a basic workflow to help you get started with Actions

name: PyTest
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pytester:
    name: running pytest
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
#      - name: Setup Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: "3.x"

      - name: install poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -

      - name: add poetry to path
        run: export PATH=$PATH:$HOME/.local/bin

      - name: run pytest in poetry env
        run: |
          cd data
          poetry install
          poetry run pytest -v
          
      
